#!/usr/bin/env bash
# Install nginx web server
apt-get update
apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.html
sed -i '/server_name _;/a\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default
sed -i '/server_name _;/a\\terror_page 404 /error.html;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/error.html
service nginx restart
