#!/usr/bin/env bash
# Add header to the server
sudo apt-get update
sudo apt-get install nginx
sudo sed -i "/location \/ {/a\\\t\tadd_header X-Served-By $(hostname);" /etc/nginx/sites-available/default
service nginx restart
