#!/usr/bin/env bash
# displays numbers from 1 to 100 FIZZBUZZ

for i in $(seq 1 100); do
    if [[ $((i%3)) == 0 && $((i%5)) == 0 ]]; then
	echo Fizzbuzz
    elif [[ $((i%3)) == 0 ]]; then
	echo Fizz
    elif [[ $((i%5)) == 0 ]]; then
	echo Buzz
    else
	echo "$i"
    fi
done
