#!/usr/bin/env bash
# Tells a story based on the contents of the `/etc/passwd` file.

while IFS=":" read user pass uid gid info h s; do
    echo "The user $user is part of the $gid gang,"\
	 "lives in $h and rides $s."\
	 "$uid's place is protected by the passcode $pass,"\
	 "more info about the user here: $info"
done < /etc/passwd
