#!/usr/bin/env bash
# Fix nginx running at port 8080 and running as root
pkill -f apache2
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod +rw /etc/nginx/nginx.conf
sed -i '1iuser nginx;' /etc/nginx/nginx.conf
sudo -u nginx /etc/init.d/nginx start
