#!/usr/bin/env bash
# Fix nginx server
pkill -f apache2
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sudo -u nginx /etc/init.d/nginx start
